export const tableNames = [
  'users',
  'oauth_login_attempts',
  'user_sessions',
  'years',
  'groups',
  'projects',
  'project_members',
  'award_categories',
  'project_nominations',
  'votes',
  'awards',
  'media',
  'project_videos',
  'video_uploads',
  'video_upload_parts',
  'video_processing_attempts',
  'screening_order',
] as const;
